### PR TITLE
Milestone #6: Web accessibility check

### PR DESCRIPTION
**Pull request by yonas44**
Web accessibility check:
- Page title - [#8](https://github.com/yonas44/Personal-Portfolio/pull/7/commits/e261d709fc320194af8a2e892b9fed257c5f90a4#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L8).
- Image text alternatives - [#14](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L14), [#42](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L42), [#50](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L50), [#58](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L58), [#66](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L58), [#74](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L74), [#80](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L80), [#197](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L197), [#204](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L204), [#216](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L216), [#226](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L226), [#237](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L237), [#290](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L290),  [#298](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L298), [#306](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L306), [#314](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L314), [#322](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L322), [#337](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L337).
- Text heading - [#27](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L27), [#206](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L206), [#70](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL70), [#291](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL291).
- Color contrast - no issue found.
- Resize - [#310](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aR310).
- Interaction - no issue found.
- Moving content - no issue found.
- Multimedia - no issue found.
- The basic structure of the page - [#54](https://github.com/yonas44/Personal-Portfolio/commit/58bcedf8e1c4d067cd2f615255e8058678a2e45b#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL54).

Thankyou for reviewing our PR!

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @yonas44, 

# Required Changes ♻️

Good job so far!
You are doing it well 👍🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct t Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] Please 🙏🏽 add a meaningful title to your page we could name the page with our name e.g. `Yonas Potfolio` instead of `Portfolio`, it describes the content of the page. The web accesibily check shoul have linked: `Page title - #8`

   > Check that there is a title that adequately and briefly describes the content of the page.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yonas44** [comment]
Okay @franclobo thankyou for the feedback i will do that.

**Review by Reem-lab — APPROVED** [review]
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯



## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the accessibilty✅
📌 Good commit messages ✅

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yonas44** [comment]
Okay thankyou @Reem-lab. We will proceed with the merge.

**Pull request merged**
